### ISSUE TITLE
error while populating zone which exists in different views

### ISSUE THREAD

**Issue by LuPo** [jcollie/octodns-netbox-dns#6]
When two zones with the same name are configured in Netbox-DNS plugin under different views ValueError is being thrown.
When view is not declared in the provider configuration  _get_nb_zone() filters the zones only by zone name and thus returns multiply responses which are not handled. 
https://github.com/jcollie/octodns-netbox-dns/blob/d0a9447e4b481f44341ba7e5be3132f4cddaff5c/octodns_netbox_dns/__init__.py#L88

**Comment by jcollie** [comment]
Closed by #7 correct?

**Comment by LuPo** [comment]
There is an issue introduced by commit [e4db78a](https://github.com/jcollie/octodns-netbox-dns/pull/7/commits/e4db78a281a27765271f1afda07dee08602ed2d0) where zones without a view will get an attribute error. I am pushing a new PR to fix it.
